# Generated by Django 2.2.14 on 2021-05-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.URLField()),
                ('encabezado', models.CharField(max_length=240)),
                ('descripcion', models.TextField(max_length=1340)),
            ],
        ),
    ]
