# Generated by Django 2.2.14 on 2021-05-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=530)),
            ],
        ),
    ]
