# Generated by Django 2.2.14 on 2021-12-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category2', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='article', to='category2.Category2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
