# Generated by Django 2.2.14 on 2021-12-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category2', '0003_auto_20211222_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=2000)),
                ('content', models.TextField(max_length=1000000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='article_comment', to='category2.Category2'),
        ),
    ]
