# Generated by Django 2.2.14 on 2021-12-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category2', '0005_auto_20211222_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='alias',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
