# Generated by Django 2.2.14 on 2021-06-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antimatter',
            name='cuerpo',
            field=models.CharField(blank=True, max_length=40000, null=True),
        ),
        migrations.AddField(
            model_name='antimatter',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='unity',
            name='cuerpo',
            field=models.CharField(blank=True, max_length=40000, null=True),
        ),
        migrations.AddField(
            model_name='unity',
            name='titulo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='cuerpo',
            field=models.CharField(blank=True, max_length=40000, null=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='titulo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='unity',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
