# Generated by Django 2.2.14 on 2021-05-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=400)),
                ('img', models.TextField(max_length=100)),
                ('action', models.TextField(max_length=100)),
            ],
        ),
    ]
